//
//  CardType.swift
//  RagnarokOffline
//
//  Generated by ROGenerator.
//

/// Converted from `e_card_type` in `map/pc.hpp`.
public enum CardType: CaseIterable, RawRepresentable, Sendable {
    case normal
    case enchant

    public var rawValue: Int {
        switch self {
        case .normal: 0
        case .enchant: 1
        }
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .normal
        case 1: self = .enchant
        default: return nil
        }
    }
}

extension CardType: CodingKey, CodingKeyRepresentable, Decodable {
    public init?(stringValue: String) {
        switch stringValue.uppercased() {
        case "NORMAL": self = .normal
        case "ENCHANT": self = .enchant
        default: return nil
        }
    }

    public init?<T>(codingKey: T) where T: CodingKey {
        self.init(stringValue: codingKey.stringValue)
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let stringValue = try container.decode(String.self)
        if let value = Self.init(stringValue: stringValue) {
            self = value
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Could not initialize \(Self.self) from invalid string value \(stringValue)")
        }
    }
}
