//
//  EAJobID.swift
//  RagnarokOffline
//
//  Generated by ROCodeGenerator.
//

/// Converted from `e_mapid` in `map/map.hpp`.
public enum EAJobID: Int, CaseIterable, Sendable {
    case novice = 0x0
    case swordman = 0x1
    case mage = 0x2
    case archer = 0x3
    case acolyte = 0x4
    case merchant = 0x5
    case thief = 0x6
    case taekwon = 0x7
    case wedding = 0x8
    case gunslinger = 0x9
    case ninja = 0xa
    case xmas = 0xb
    case summer = 0xc
    case hanbok = 0xd
    case gangsi = 0xe
    case oktoberfest = 0xf
    case summoner = 0x10
    case summer2 = 0x11
    case super_novice = 0x100
    case knight = 0x101
    case wizard = 0x102
    case hunter = 0x103
    case priest = 0x104
    case blacksmith = 0x105
    case assassin = 0x106
    case star_gladiator = 0x107
    case rebellion = 0x109
    case kagerouoboro = 0x10a
    case death_knight = 0x10e
    case crusader = 0x201
    case sage = 0x202
    case barddancer = 0x203
    case monk = 0x204
    case alchemist = 0x205
    case rogue = 0x206
    case soul_linker = 0x207
    case dark_collector = 0x20e
    case novice_high = 0x1000
    case swordman_high = 0x1001
    case mage_high = 0x1002
    case archer_high = 0x1003
    case acolyte_high = 0x1004
    case merchant_high = 0x1005
    case thief_high = 0x1006
    case lord_knight = 0x1101
    case high_wizard = 0x1102
    case sniper = 0x1103
    case high_priest = 0x1104
    case whitesmith = 0x1105
    case assassin_cross = 0x1106
    case paladin = 0x1201
    case professor = 0x1202
    case clowngypsy = 0x1203
    case champion = 0x1204
    case creator = 0x1205
    case stalker = 0x1206
    case baby = 0x2000
    case baby_swordman = 0x2001
    case baby_mage = 0x2002
    case baby_archer = 0x2003
    case baby_acolyte = 0x2004
    case baby_merchant = 0x2005
    case baby_thief = 0x2006
    case baby_taekwon = 0x2007
    case baby_gunslinger = 0x2009
    case baby_ninja = 0x200a
    case baby_summoner = 0x2010
    case super_baby = 0x2100
    case baby_knight = 0x2101
    case baby_wizard = 0x2102
    case baby_hunter = 0x2103
    case baby_priest = 0x2104
    case baby_blacksmith = 0x2105
    case baby_assassin = 0x2106
    case baby_star_gladiator = 0x2107
    case baby_rebellion = 0x2109
    case baby_kagerouoboro = 0x210a
    case baby_crusader = 0x2201
    case baby_sage = 0x2202
    case baby_barddancer = 0x2203
    case baby_monk = 0x2204
    case baby_alchemist = 0x2205
    case baby_rogue = 0x2206
    case baby_soul_linker = 0x2207
    case super_novice_e = 0x4100
    case rune_knight = 0x4101
    case warlock = 0x4102
    case ranger = 0x4103
    case arch_bishop = 0x4104
    case mechanic = 0x4105
    case guillotine_cross = 0x4106
    case star_emperor = 0x4107
    case royal_guard = 0x4201
    case sorcerer = 0x4202
    case minstrelwanderer = 0x4203
    case sura = 0x4204
    case genetic = 0x4205
    case shadow_chaser = 0x4206
    case soul_reaper = 0x4207
    case rune_knight_t = 0x5101
    case warlock_t = 0x5102
    case ranger_t = 0x5103
    case arch_bishop_t = 0x5104
    case mechanic_t = 0x5105
    case guillotine_cross_t = 0x5106
    case royal_guard_t = 0x5201
    case sorcerer_t = 0x5202
    case minstrelwanderer_t = 0x5203
    case sura_t = 0x5204
    case genetic_t = 0x5205
    case shadow_chaser_t = 0x5206
    case super_baby_e = 0x6100
    case baby_rune_knight = 0x6101
    case baby_warlock = 0x6102
    case baby_ranger = 0x6103
    case baby_arch_bishop = 0x6104
    case baby_mechanic = 0x6105
    case baby_guillotine_cross = 0x6106
    case baby_star_emperor = 0x6107
    case baby_royal_guard = 0x6201
    case baby_sorcerer = 0x6202
    case baby_minstrelwanderer = 0x6203
    case baby_sura = 0x6204
    case baby_genetic = 0x6205
    case baby_shadow_chaser = 0x6206
    case baby_soul_reaper = 0x6207
    case hyper_novice = 0xd100
    case dragon_knight = 0xd101
    case arch_mage = 0xd102
    case windhawk = 0xd103
    case cardinal = 0xd104
    case meister = 0xd105
    case shadow_cross = 0xd106
    case sky_emperor = 0xd107
    case night_watch = 0xd109
    case shinkiro_shiranui = 0xd10a
    case spirit_handler = 0xd110
    case imperial_guard = 0xd201
    case elemental_master = 0xd202
    case troubadourtrouvere = 0xd203
    case inquisitor = 0xd204
    case biolo = 0xd205
    case abyss_chaser = 0xd206
    case soul_ascetic = 0xd207
}

extension EAJobID: CodingKey {
    public var stringValue: String {
        switch self {
        case .novice: "NOVICE"
        case .swordman: "SWORDMAN"
        case .mage: "MAGE"
        case .archer: "ARCHER"
        case .acolyte: "ACOLYTE"
        case .merchant: "MERCHANT"
        case .thief: "THIEF"
        case .taekwon: "TAEKWON"
        case .wedding: "WEDDING"
        case .gunslinger: "GUNSLINGER"
        case .ninja: "NINJA"
        case .xmas: "XMAS"
        case .summer: "SUMMER"
        case .hanbok: "HANBOK"
        case .gangsi: "GANGSI"
        case .oktoberfest: "OKTOBERFEST"
        case .summoner: "SUMMONER"
        case .summer2: "SUMMER2"
        case .super_novice: "SUPER_NOVICE"
        case .knight: "KNIGHT"
        case .wizard: "WIZARD"
        case .hunter: "HUNTER"
        case .priest: "PRIEST"
        case .blacksmith: "BLACKSMITH"
        case .assassin: "ASSASSIN"
        case .star_gladiator: "STAR_GLADIATOR"
        case .rebellion: "REBELLION"
        case .kagerouoboro: "KAGEROUOBORO"
        case .death_knight: "DEATH_KNIGHT"
        case .crusader: "CRUSADER"
        case .sage: "SAGE"
        case .barddancer: "BARDDANCER"
        case .monk: "MONK"
        case .alchemist: "ALCHEMIST"
        case .rogue: "ROGUE"
        case .soul_linker: "SOUL_LINKER"
        case .dark_collector: "DARK_COLLECTOR"
        case .novice_high: "NOVICE_HIGH"
        case .swordman_high: "SWORDMAN_HIGH"
        case .mage_high: "MAGE_HIGH"
        case .archer_high: "ARCHER_HIGH"
        case .acolyte_high: "ACOLYTE_HIGH"
        case .merchant_high: "MERCHANT_HIGH"
        case .thief_high: "THIEF_HIGH"
        case .lord_knight: "LORD_KNIGHT"
        case .high_wizard: "HIGH_WIZARD"
        case .sniper: "SNIPER"
        case .high_priest: "HIGH_PRIEST"
        case .whitesmith: "WHITESMITH"
        case .assassin_cross: "ASSASSIN_CROSS"
        case .paladin: "PALADIN"
        case .professor: "PROFESSOR"
        case .clowngypsy: "CLOWNGYPSY"
        case .champion: "CHAMPION"
        case .creator: "CREATOR"
        case .stalker: "STALKER"
        case .baby: "BABY"
        case .baby_swordman: "BABY_SWORDMAN"
        case .baby_mage: "BABY_MAGE"
        case .baby_archer: "BABY_ARCHER"
        case .baby_acolyte: "BABY_ACOLYTE"
        case .baby_merchant: "BABY_MERCHANT"
        case .baby_thief: "BABY_THIEF"
        case .baby_taekwon: "BABY_TAEKWON"
        case .baby_gunslinger: "BABY_GUNSLINGER"
        case .baby_ninja: "BABY_NINJA"
        case .baby_summoner: "BABY_SUMMONER"
        case .super_baby: "SUPER_BABY"
        case .baby_knight: "BABY_KNIGHT"
        case .baby_wizard: "BABY_WIZARD"
        case .baby_hunter: "BABY_HUNTER"
        case .baby_priest: "BABY_PRIEST"
        case .baby_blacksmith: "BABY_BLACKSMITH"
        case .baby_assassin: "BABY_ASSASSIN"
        case .baby_star_gladiator: "BABY_STAR_GLADIATOR"
        case .baby_rebellion: "BABY_REBELLION"
        case .baby_kagerouoboro: "BABY_KAGEROUOBORO"
        case .baby_crusader: "BABY_CRUSADER"
        case .baby_sage: "BABY_SAGE"
        case .baby_barddancer: "BABY_BARDDANCER"
        case .baby_monk: "BABY_MONK"
        case .baby_alchemist: "BABY_ALCHEMIST"
        case .baby_rogue: "BABY_ROGUE"
        case .baby_soul_linker: "BABY_SOUL_LINKER"
        case .super_novice_e: "SUPER_NOVICE_E"
        case .rune_knight: "RUNE_KNIGHT"
        case .warlock: "WARLOCK"
        case .ranger: "RANGER"
        case .arch_bishop: "ARCH_BISHOP"
        case .mechanic: "MECHANIC"
        case .guillotine_cross: "GUILLOTINE_CROSS"
        case .star_emperor: "STAR_EMPEROR"
        case .royal_guard: "ROYAL_GUARD"
        case .sorcerer: "SORCERER"
        case .minstrelwanderer: "MINSTRELWANDERER"
        case .sura: "SURA"
        case .genetic: "GENETIC"
        case .shadow_chaser: "SHADOW_CHASER"
        case .soul_reaper: "SOUL_REAPER"
        case .rune_knight_t: "RUNE_KNIGHT_T"
        case .warlock_t: "WARLOCK_T"
        case .ranger_t: "RANGER_T"
        case .arch_bishop_t: "ARCH_BISHOP_T"
        case .mechanic_t: "MECHANIC_T"
        case .guillotine_cross_t: "GUILLOTINE_CROSS_T"
        case .royal_guard_t: "ROYAL_GUARD_T"
        case .sorcerer_t: "SORCERER_T"
        case .minstrelwanderer_t: "MINSTRELWANDERER_T"
        case .sura_t: "SURA_T"
        case .genetic_t: "GENETIC_T"
        case .shadow_chaser_t: "SHADOW_CHASER_T"
        case .super_baby_e: "SUPER_BABY_E"
        case .baby_rune_knight: "BABY_RUNE_KNIGHT"
        case .baby_warlock: "BABY_WARLOCK"
        case .baby_ranger: "BABY_RANGER"
        case .baby_arch_bishop: "BABY_ARCH_BISHOP"
        case .baby_mechanic: "BABY_MECHANIC"
        case .baby_guillotine_cross: "BABY_GUILLOTINE_CROSS"
        case .baby_star_emperor: "BABY_STAR_EMPEROR"
        case .baby_royal_guard: "BABY_ROYAL_GUARD"
        case .baby_sorcerer: "BABY_SORCERER"
        case .baby_minstrelwanderer: "BABY_MINSTRELWANDERER"
        case .baby_sura: "BABY_SURA"
        case .baby_genetic: "BABY_GENETIC"
        case .baby_shadow_chaser: "BABY_SHADOW_CHASER"
        case .baby_soul_reaper: "BABY_SOUL_REAPER"
        case .hyper_novice: "HYPER_NOVICE"
        case .dragon_knight: "DRAGON_KNIGHT"
        case .arch_mage: "ARCH_MAGE"
        case .windhawk: "WINDHAWK"
        case .cardinal: "CARDINAL"
        case .meister: "MEISTER"
        case .shadow_cross: "SHADOW_CROSS"
        case .sky_emperor: "SKY_EMPEROR"
        case .night_watch: "NIGHT_WATCH"
        case .shinkiro_shiranui: "SHINKIRO_SHIRANUI"
        case .spirit_handler: "SPIRIT_HANDLER"
        case .imperial_guard: "IMPERIAL_GUARD"
        case .elemental_master: "ELEMENTAL_MASTER"
        case .troubadourtrouvere: "TROUBADOURTROUVERE"
        case .inquisitor: "INQUISITOR"
        case .biolo: "BIOLO"
        case .abyss_chaser: "ABYSS_CHASER"
        case .soul_ascetic: "SOUL_ASCETIC"
        }
    }

    public init?(stringValue: String) {
        switch stringValue.uppercased() {
        case "NOVICE": self = .novice
        case "SWORDMAN": self = .swordman
        case "MAGE": self = .mage
        case "ARCHER": self = .archer
        case "ACOLYTE": self = .acolyte
        case "MERCHANT": self = .merchant
        case "THIEF": self = .thief
        case "TAEKWON": self = .taekwon
        case "WEDDING": self = .wedding
        case "GUNSLINGER": self = .gunslinger
        case "NINJA": self = .ninja
        case "XMAS": self = .xmas
        case "SUMMER": self = .summer
        case "HANBOK": self = .hanbok
        case "GANGSI": self = .gangsi
        case "OKTOBERFEST": self = .oktoberfest
        case "SUMMONER": self = .summoner
        case "SUMMER2": self = .summer2
        case "SUPER_NOVICE", "SUPERNOVICE": self = .super_novice
        case "KNIGHT": self = .knight
        case "WIZARD": self = .wizard
        case "HUNTER": self = .hunter
        case "PRIEST": self = .priest
        case "BLACKSMITH": self = .blacksmith
        case "ASSASSIN": self = .assassin
        case "STAR_GLADIATOR": self = .star_gladiator
        case "REBELLION": self = .rebellion
        case "KAGEROUOBORO": self = .kagerouoboro
        case "DEATH_KNIGHT": self = .death_knight
        case "CRUSADER": self = .crusader
        case "SAGE": self = .sage
        case "BARDDANCER": self = .barddancer
        case "MONK": self = .monk
        case "ALCHEMIST": self = .alchemist
        case "ROGUE": self = .rogue
        case "SOUL_LINKER": self = .soul_linker
        case "DARK_COLLECTOR": self = .dark_collector
        case "NOVICE_HIGH": self = .novice_high
        case "SWORDMAN_HIGH": self = .swordman_high
        case "MAGE_HIGH": self = .mage_high
        case "ARCHER_HIGH": self = .archer_high
        case "ACOLYTE_HIGH": self = .acolyte_high
        case "MERCHANT_HIGH": self = .merchant_high
        case "THIEF_HIGH": self = .thief_high
        case "LORD_KNIGHT": self = .lord_knight
        case "HIGH_WIZARD": self = .high_wizard
        case "SNIPER": self = .sniper
        case "HIGH_PRIEST": self = .high_priest
        case "WHITESMITH": self = .whitesmith
        case "ASSASSIN_CROSS": self = .assassin_cross
        case "PALADIN": self = .paladin
        case "PROFESSOR": self = .professor
        case "CLOWNGYPSY": self = .clowngypsy
        case "CHAMPION": self = .champion
        case "CREATOR": self = .creator
        case "STALKER": self = .stalker
        case "BABY": self = .baby
        case "BABY_SWORDMAN": self = .baby_swordman
        case "BABY_MAGE": self = .baby_mage
        case "BABY_ARCHER": self = .baby_archer
        case "BABY_ACOLYTE": self = .baby_acolyte
        case "BABY_MERCHANT": self = .baby_merchant
        case "BABY_THIEF": self = .baby_thief
        case "BABY_TAEKWON": self = .baby_taekwon
        case "BABY_GUNSLINGER": self = .baby_gunslinger
        case "BABY_NINJA": self = .baby_ninja
        case "BABY_SUMMONER": self = .baby_summoner
        case "SUPER_BABY": self = .super_baby
        case "BABY_KNIGHT": self = .baby_knight
        case "BABY_WIZARD": self = .baby_wizard
        case "BABY_HUNTER": self = .baby_hunter
        case "BABY_PRIEST": self = .baby_priest
        case "BABY_BLACKSMITH": self = .baby_blacksmith
        case "BABY_ASSASSIN": self = .baby_assassin
        case "BABY_STAR_GLADIATOR": self = .baby_star_gladiator
        case "BABY_REBELLION": self = .baby_rebellion
        case "BABY_KAGEROUOBORO": self = .baby_kagerouoboro
        case "BABY_CRUSADER": self = .baby_crusader
        case "BABY_SAGE": self = .baby_sage
        case "BABY_BARDDANCER": self = .baby_barddancer
        case "BABY_MONK": self = .baby_monk
        case "BABY_ALCHEMIST": self = .baby_alchemist
        case "BABY_ROGUE": self = .baby_rogue
        case "BABY_SOUL_LINKER": self = .baby_soul_linker
        case "SUPER_NOVICE_E": self = .super_novice_e
        case "RUNE_KNIGHT": self = .rune_knight
        case "WARLOCK": self = .warlock
        case "RANGER": self = .ranger
        case "ARCH_BISHOP": self = .arch_bishop
        case "MECHANIC": self = .mechanic
        case "GUILLOTINE_CROSS": self = .guillotine_cross
        case "STAR_EMPEROR": self = .star_emperor
        case "ROYAL_GUARD": self = .royal_guard
        case "SORCERER": self = .sorcerer
        case "MINSTRELWANDERER": self = .minstrelwanderer
        case "SURA": self = .sura
        case "GENETIC": self = .genetic
        case "SHADOW_CHASER": self = .shadow_chaser
        case "SOUL_REAPER": self = .soul_reaper
        case "RUNE_KNIGHT_T": self = .rune_knight_t
        case "WARLOCK_T": self = .warlock_t
        case "RANGER_T": self = .ranger_t
        case "ARCH_BISHOP_T": self = .arch_bishop_t
        case "MECHANIC_T": self = .mechanic_t
        case "GUILLOTINE_CROSS_T": self = .guillotine_cross_t
        case "ROYAL_GUARD_T": self = .royal_guard_t
        case "SORCERER_T": self = .sorcerer_t
        case "MINSTRELWANDERER_T": self = .minstrelwanderer_t
        case "SURA_T": self = .sura_t
        case "GENETIC_T": self = .genetic_t
        case "SHADOW_CHASER_T": self = .shadow_chaser_t
        case "SUPER_BABY_E": self = .super_baby_e
        case "BABY_RUNE_KNIGHT": self = .baby_rune_knight
        case "BABY_WARLOCK": self = .baby_warlock
        case "BABY_RANGER": self = .baby_ranger
        case "BABY_ARCH_BISHOP": self = .baby_arch_bishop
        case "BABY_MECHANIC": self = .baby_mechanic
        case "BABY_GUILLOTINE_CROSS": self = .baby_guillotine_cross
        case "BABY_STAR_EMPEROR": self = .baby_star_emperor
        case "BABY_ROYAL_GUARD": self = .baby_royal_guard
        case "BABY_SORCERER": self = .baby_sorcerer
        case "BABY_MINSTRELWANDERER": self = .baby_minstrelwanderer
        case "BABY_SURA": self = .baby_sura
        case "BABY_GENETIC": self = .baby_genetic
        case "BABY_SHADOW_CHASER": self = .baby_shadow_chaser
        case "BABY_SOUL_REAPER": self = .baby_soul_reaper
        case "HYPER_NOVICE": self = .hyper_novice
        case "DRAGON_KNIGHT": self = .dragon_knight
        case "ARCH_MAGE": self = .arch_mage
        case "WINDHAWK": self = .windhawk
        case "CARDINAL": self = .cardinal
        case "MEISTER": self = .meister
        case "SHADOW_CROSS": self = .shadow_cross
        case "SKY_EMPEROR": self = .sky_emperor
        case "NIGHT_WATCH": self = .night_watch
        case "SHINKIRO_SHIRANUI": self = .shinkiro_shiranui
        case "SPIRIT_HANDLER": self = .spirit_handler
        case "IMPERIAL_GUARD": self = .imperial_guard
        case "ELEMENTAL_MASTER": self = .elemental_master
        case "TROUBADOURTROUVERE": self = .troubadourtrouvere
        case "INQUISITOR": self = .inquisitor
        case "BIOLO": self = .biolo
        case "ABYSS_CHASER": self = .abyss_chaser
        case "SOUL_ASCETIC": self = .soul_ascetic
        default: return nil
        }
    }

    public var intValue: Int? {
        rawValue
    }

    public init?(intValue: Int) {
        self.init(rawValue: intValue)
    }
}

extension EAJobID: CodingKeyRepresentable {
    public var codingKey: any CodingKey {
        self
    }

    public init?<T>(codingKey: T) where T: CodingKey {
        self.init(stringValue: codingKey.stringValue)
    }
}

extension EAJobID: Decodable {
    public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let stringValue = try container.decode(String.self)
        if let value = Self.init(stringValue: stringValue) {
            self = value
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Could not initialize \(Self.self) from invalid string value \(stringValue)")
        }
    }
}
