//
//  Sex.swift
//  RagnarokOffline
//
//  Generated by ROCodeGenerator.
//

/// Converted from `e_sex` in `common/mmo.hpp`.
public enum Sex: Int, CaseIterable, Sendable {
    case female = 0
    case male = 1
    case both = 2
}

extension Sex: CodingKey {
    public var stringValue: String {
        switch self {
        case .female: "FEMALE"
        case .male: "MALE"
        case .both: "BOTH"
        }
    }

    public init?(stringValue: String) {
        switch stringValue.uppercased() {
        case "FEMALE": self = .female
        case "MALE": self = .male
        case "BOTH": self = .both
        default: return nil
        }
    }

    public var intValue: Int? {
        rawValue
    }

    public init?(intValue: Int) {
        self.init(rawValue: intValue)
    }
}

extension Sex: CodingKeyRepresentable {
    public var codingKey: any CodingKey {
        self
    }

    public init?<T>(codingKey: T) where T: CodingKey {
        self.init(stringValue: codingKey.stringValue)
    }
}

extension Sex: Decodable {
    public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let stringValue = try container.decode(String.self)
        if let value = Self.init(stringValue: stringValue) {
            self = value
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Could not initialize \(Self.self) from invalid string value \(stringValue)")
        }
    }
}
