//
//  SkillCastFlag.swift
//  RagnarokOffline
//
//  Generated by ROGenerator.
//

/// Converted from `e_skill_cast_flags` in `map/skill.hpp`.
public enum SkillCastFlag: CaseIterable, RawRepresentable, Sendable {
    case ignoredex
    case ignorestatus
    case ignoreitembonus

    public var rawValue: Int {
        switch self {
        case .ignoredex: 0x1
        case .ignorestatus: 0x2
        case .ignoreitembonus: 0x4
        }
    }

    public init?(rawValue: Int) {
        switch rawValue {
        case 0x1: self = .ignoredex
        case 0x2: self = .ignorestatus
        case 0x4: self = .ignoreitembonus
        default: return nil
        }
    }
}

extension SkillCastFlag: CodingKey, CodingKeyRepresentable, Decodable {
    public init?(stringValue: String) {
        switch stringValue.uppercased() {
        case "IGNOREDEX": self = .ignoredex
        case "IGNORESTATUS": self = .ignorestatus
        case "IGNOREITEMBONUS": self = .ignoreitembonus
        default: return nil
        }
    }

    public init?<T>(codingKey: T) where T: CodingKey {
        self.init(stringValue: codingKey.stringValue)
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let stringValue = try container.decode(String.self)
        if let value = Self.init(stringValue: stringValue) {
            self = value
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Could not initialize \(Self.self) from invalid string value \(stringValue)")
        }
    }
}
