//
//  GeneratePacketsCommand.swift
//  ROTools
//
//  Created by Leon Li on 2024/10/18.
//

import ArgumentParser
import Foundation
import SwiftSyntax
import SwiftSyntaxBuilder

struct GeneratePacketsCommand: ParsableCommand {
    static let configuration = CommandConfiguration(commandName: "generate-packets")

    @Argument(transform: { URL(filePath: $0, directoryHint: .isDirectory) })
    var rathenaDirectory: URL

    @Argument(transform: { URL(filePath: $0, directoryHint: .isDirectory) })
    var generatedDirectory: URL

    mutating func run() throws {
        try? FileManager.default.removeItem(at: generatedDirectory)
        try? FileManager.default.createDirectory(at: generatedDirectory, withIntermediateDirectories: true)

        try generate_packets()
        try generate_packetdb()
    }

    // MARK: - generate packets

    func generate_packets() throws {
        let dumper = ASTDumper(rathenaDirectory: rathenaDirectory)
        let asts = try [
            dumper.dump(path: "common/packets.hpp"),
            dumper.dump(path: "char/packets.hpp"),
            dumper.dump(path: "map/packets.hpp"),
        ]

        let outputName = "packets"
        var output = """
        //
        //  \(outputName).swift
        //  RagnarokOffline
        //
        //  Generated by ROCodeGenerator.
        //
        
        import ROCore
        
        """

        var headers: [ASTNode] = []
        for ast in asts {
            let nodes = ast.findNodes {
                $0.kind == "VarDecl" && $0.name != nil && $0.name!.hasPrefix("HEADER_")
            }

            for node in nodes {
                if !headers.contains(where: { $0.name! == node.name! }) {
                    headers.append(node)
                }
            }
        }
        for header in headers {
            let value = header.findNode(where: { $0.kind == "IntegerLiteral" })!.value!.intValue!
            output.append("\n")
            output.append("public let " + header.name! + ": Int16 = 0x" + String(value, radix: 16))
        }
        output.append("\n")

        let enumDecl = asts.last!.findEnumDecl(named: "packet_headers")!
        let enumConstantDecls = enumDecl.findEnumConstantDecls()
        for enumConstantDecl in enumConstantDecls {
            let name = enumConstantDecl.name!
            let value = enumConstantDecl.findConstantExpr()!.value!.intValue!
            output.append("\n")
            output.append("public let packet_header_" + name + ": Int16 = 0x" + String(value, radix: 16))
        }
        output.append("\n")

        var structDecls: [StructDecl] = []
        var referencedStructDecls: [StructDecl] = []

        for ast in asts {
            let nodes = ast.findNodes { node in
                guard node.kind == "CXXRecordDecl" else { return false }
                guard let name = node.name, name.hasPrefix("PACKET_") || name.hasPrefix("packet_") else { return false }
                guard node.inner != nil else { return false }
                return true
            }

            for node in nodes {
                if structDecls.contains(where: { $0.name == node.name }) {
                    continue
                }

                let structDecl = StructDecl(node: node)
                structDecls.append(structDecl)

                for field in structDecl.fields {
                    let structure = switch field.type {
                    case .structure(let structure):
                        structure
                    case .array(let structure):
                        structure
                    case .fixedSizeArray(let structure, _):
                        structure
                    case .string, .fixedLengthString:
                        StructureType.char
                    }
                    guard case .custom(let name) = structure else {
                        continue
                    }
                    guard let node = ast.findNode(where: { $0.kind == "CXXRecordDecl" && $0.name == name && $0.inner != nil }) else {
                        continue
                    }
                    guard !referencedStructDecls.contains(where: { $0.name == node.name }) &&
                        !structDecls.contains(where: { $0.name == node.name }) else {
                        continue
                    }

                    print(name)

                    let structDecl = StructDecl(node: node)
                    referencedStructDecls.append(structDecl)
                }
            }
        }

        for (s, structDecl) in structDecls.enumerated() {
            switch structDecl.name {
            case "PACKET_ZC_POSITION_ID_NAME_INFO":
                var nestedStructDecl = structDecl.nestedStructs[0]
                nestedStructDecl.name = "PACKET_ZC_POSITION_ID_NAME_INFO_sub"
                referencedStructDecls.append(nestedStructDecl)
            case "packet_roulette_info_ack":
                var nestedStructDecl = structDecl.nestedStructs[0]
                nestedStructDecl.name = "packet_roulette_info_ack_sub"
                referencedStructDecls.append(nestedStructDecl)
            default:
                break
            }

            for (f, fieldDecl) in structDecl.fields.enumerated() {
                switch f {
                case 0:
                    switch fieldDecl.name {
                    case "packetType", "PacketType", "packet_id":
                        structDecls[s].fields[f].name = "packetType"
                        structDecls[s].fields[f].type = .structure(.int16)
                    default:
                        break
                    }
                case 1:
                    switch fieldDecl.name {
                    case "packetLength", "PacketLength", "packetLen", "packet_len", "packetSize", "length":
                        structDecls[s].fields[f].name = "packetLength"
                        structDecls[s].fields[f].type = .structure(.int16)
                    default:
                        break
                    }
                default:
                    break
                }

                switch fieldDecl.name {
                case "list" where structDecl.name == "packet_itemlist_normal" || structDecl.name == "packet_itemlist_equip":
                    structDecls[s].fields[f].type = .array(fieldDecl.type.structRef!)
                default:
                    break
                }

                if structDecl.name == "PACKET_ZC_POSITION_ID_NAME_INFO" && fieldDecl.name == "posInfo" {
                    if case .fixedSizeArray(_, let size) = fieldDecl.type {
                        structDecls[s].fields[f].type = .fixedSizeArray(.custom("PACKET_ZC_POSITION_ID_NAME_INFO_sub"), size)
                    }
                } else if structDecl.name == "packet_roulette_info_ack" && fieldDecl.name == "ItemInfo" {
                    if case .fixedSizeArray(_, let size) = fieldDecl.type {
                        structDecls[s].fields[f].type = .fixedSizeArray(.custom("packet_roulette_info_ack_sub"), size)
                    }
                } else if structDecl.name == "packet_maptypeproperty2" && fieldDecl.name == "flag" {
                    structDecls[s].fields[f].type = structDecl.nestedStructs[0].fields[0].type
                }
            }
        }

        for (s, structDecl) in referencedStructDecls.enumerated() {
            for (f, fieldDecl) in structDecl.fields.enumerated() {
                if structDecl.name == "EQUIPITEM_INFO" && fieldDecl.name == "Flag" {
                    referencedStructDecls[s].fields[f].type = structDecl.nestedStructs[0].fields[0].type
                } else if structDecl.name == "NORMALITEM_INFO" && fieldDecl.name == "Flag" {
                    referencedStructDecls[s].fields[f].type = structDecl.nestedStructs[0].fields[0].type
                }
            }
        }

        for structDecl in structDecls + referencedStructDecls {
            if structDecl.name == "packet_quest_list_info" {
                continue
            }

            var properties: [String] = []
            var decodes: [String] = []
            var encodes: [String] = []

            for (f, field) in structDecl.fields.enumerated() {
                switch field.type {
                case .structure, .array, .string:
                    properties.append("""
                        public var \(field.name): \(field.type.annotation) = \(field.type.initialValue)
                    """)
                case .fixedSizeArray(let structure, let size):
                    properties.append("""
                        @FixedSizeArray(size: \(size), initialValue: \(structure.initialValue))
                        public var \(field.name): \(field.type.annotation)
                    """)
                case .fixedLengthString(let lengthOfBytes):
                    properties.append("""
                        @FixedLengthString(lengthOfBytes: \(lengthOfBytes))
                        public var \(field.name): \(field.type.annotation)
                    """)
                }

                var decodeExpr = ""
                switch field.type {
                case .structure(let structure):
                    decodeExpr = """
                            \(field.name) = try decoder.decode(\(structure.name).self)
                    """
                case .array(let structure):
                    let sizes = structDecl.fields[0..<f].map {
                        byteCount(forFieldType: $0.type, structDecls: structDecls + referencedStructDecls)
                    }
                    let remaining = "(Int(packetLength) - (\(sizes.joined(separator: " + "))))"
                    let structByteCount = byteCount(forStructRef: structure, structDecls: structDecls + referencedStructDecls)
                    decodeExpr = """
                            \(field.name) = try decoder.decode([\(structure.name)].self, count: \(remaining) / \(structByteCount))
                    """
                case .fixedSizeArray(let structure, let size):
                    decodeExpr = """
                            \(field.name) = try decoder.decode([\(structure.name)].self, count: \(size))
                    """
                case .string:
                    let sizes = structDecl.fields[0..<f].map {
                        byteCount(forFieldType: $0.type, structDecls: structDecls + referencedStructDecls)
                    }
                    let remaining = "(Int(packetLength) - (\(sizes.joined(separator: " + "))))"
                    decodeExpr = """
                            \(field.name) = try decoder.decode(String.self, lengthOfBytes: \(remaining))
                    """
                case .fixedLengthString(let lengthOfBytes):
                    decodeExpr = """
                            \(field.name) = try decoder.decode(String.self, lengthOfBytes: \(lengthOfBytes))
                    """
                }
                if structDecl.name == "packet_quest_add_header", field.name == "objectives" {
                    decodeExpr = """
                            \(field.name) = try decoder.decode([\(field.type.structRef!.name)].self, count: Int(count))
                    """
                }
                decodes.append(decodeExpr)

                switch field.type {
                case .structure, .array, .fixedSizeArray, .string:
                    encodes.append("""
                            try encoder.encode(\(field.name))
                    """)
                case .fixedLengthString(let lengthOfBytes):
                    encodes.append("""
                            try encoder.encode(\(field.name), lengthOfBytes: \(lengthOfBytes))
                    """)
                }
            }

            output.append("""
            
            public struct \(structDecl.name): BinaryDecodable, BinaryEncodable, Sendable {
                public static var size: Int {
                    \(byteCount(forStructRef: .custom(structDecl.name), structDecls: structDecls + referencedStructDecls))
                }
            \(properties.joined(separator: "\n"))
                public init() {
                }
                public init(from decoder: BinaryDecoder) throws {
            \(decodes.joined(separator: "\n"))
                }
                public func encode(to encoder: BinaryEncoder) throws {
            \(encodes.joined(separator: "\n"))
                }
            }
            
            """)
        }

        let outputURL = generatedDirectory.appending(path: "\(outputName).swift")
        try output.write(to: outputURL, atomically: true, encoding: .utf8)
    }

    func byteCount(forFieldType fieldType: FieldType, structDecls: [StructDecl]) -> String {
        switch fieldType {
        case .structure(let structRef):
            byteCount(forStructRef: structRef, structDecls: structDecls)
        case .array:
            "?"
        case .fixedSizeArray(let structRef, let size):
            "(" + byteCount(forStructRef: structRef, structDecls: structDecls) + " * \(size))"
        case .string:
            "?"
        case .fixedLengthString(let lengthOfBytes):
            "\(lengthOfBytes)"
        }
    }

    func byteCount(forStructRef structRef: StructureType, structDecls: [StructDecl]) -> String {
        switch structRef {
        case .char:
            return "1"
        case .int8:
            return "1"
        case .uint8:
            return "1"
        case .int16:
            return "2"
        case .uint16:
            return "2"
        case .int32:
            return "4"
        case .uint32:
            return "4"
        case .int64:
            return "8"
        case .uint64:
            return "8"
        case .float:
            return "4"
        case .double:
            return "8"
        case .custom(let name):
            let structDecl = structDecls.first {
                $0.name == name
            }!
            let size = structDecl.fields.map {
                byteCount(forFieldType: $0.type, structDecls: structDecls)
            }.joined(separator: " + ")
            return size.contains("?") ? "-1" : "(\(size))"
        }
    }

    // MARK: - generate packetdb

    func generate_packetdb() throws {
        let dumper = ASTDumper(rathenaDirectory: rathenaDirectory)
        let ast = try dumper.dump(path: "map/clif.cpp")

        let readdb = ast.findFunctionDecl(named: "packetdb_readdb")!
        let addpackets = readdb.findCallExprs(fn: "packetdb_addpacket")

        var outputLines: [String] = []

        for addpacket in addpackets {
            let packetTypeNode = addpacket.inner![1].findNode { node in
                node.kind == "IntegerLiteral" || node.kind == "DeclRefExpr"
            }!
            var packetType: String
            if let intValue = packetTypeNode.value?.intValue {
                packetType = "0x" + String(intValue, radix: 16)
            } else {
                packetType = packetTypeNode.referencedDecl!.name!
                if !packetType.hasPrefix("HEADER_") {
                    packetType = "packet_header_" + packetType
                }
            }

            let packetLengthNode = addpacket.inner![2].findNode { node in
                node.kind == "IntegerLiteral" || node.kind == "UnaryExprOrTypeTraitExpr"
            }!
            var packetLength: String
            if let intValue = packetLengthNode.value?.intValue {
                packetLength = "\(intValue)"
                if addpacket.inner![2].findNode(where: { $0.kind == "UnaryOperator" && $0.opcode == "-" }) != nil {
                    packetLength = "-" + packetLength
                }
            } else {
                packetLength = "\(packetLengthNode.argType!.desugaredQualType!).size"
            }

            let functionNameNode = addpacket.inner![3].findNode { node in
                node.referencedDecl?.kind == "FunctionDecl"
            }
            let nullableFunctionName = functionNameNode?.referencedDecl?.name
            let functionName = nullableFunctionName == nil ? "nil" : "\"\(nullableFunctionName!)\""

            let offsetsNode = addpacket.inner![4...].map { node in
                node.findNode(where: { $0.kind == "IntegerLiteral" })!.value!.intValue!
            }
            let offsets = "[" + offsetsNode.dropLast().map(String.init).joined(separator: ", ") + "]"

            outputLines.append("add_packet(\(packetType), \(packetLength), \(functionName), \(offsets))")
        }

        let packetdbLines = outputLines
            .map({ "    \($0)" })
            .joined(separator: "\n")
        let packetdbOutputContents = """
        public func add_packets(_ add_packet: (Int16, Int, String?, [Int]) -> Void) {
        \(packetdbLines)
        }
        
        """

        let packetdbOutputURL = generatedDirectory.appending(path: "packetdb.swift")
        try packetdbOutputContents.write(to: packetdbOutputURL, atomically: true, encoding: .utf8)
    }
}
