//
//  Sex.swift
//  RagnarokOffline
//
//  Generated by ROGenerator.
//

public enum Sex: Int, CodingKey, CodingKeyRepresentable, Decodable, Sendable {
    case female = 0
    case male
    case both

    public init?(stringValue: String) {
        switch stringValue.uppercased() {
        case "FEMALE": self = .female
        case "MALE": self = .male
        case "BOTH": self = .both
        default: return nil
        }
    }

    public init?<T>(codingKey: T) where T: CodingKey {
        self.init(stringValue: codingKey.stringValue)
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let stringValue = try container.decode(String.self)
        if let value = Self.init(stringValue: stringValue) {
            self = value
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Could not initialize \(Self.self) from invalid string value \(stringValue)")
        }
    }
}
