//
//  PacketRegistry.swift
//  RagnarokOffline
//
//  Created by Leon Li on 2025/3/24.
//

import BinaryIO

public typealias RegisteredPacket = BinaryDecodable & Sendable

let registeredPackets: [Int16 : any RegisteredPacket.Type] = [
    HEADER_SC_NOTIFY_BAN: PACKET_SC_NOTIFY_BAN.self,

    HEADER_AC_ACCEPT_LOGIN: PACKET_AC_ACCEPT_LOGIN.self,
    HEADER_AC_REFUSE_LOGIN: PACKET_AC_REFUSE_LOGIN.self,
    HEADER_AC_ACK_HASH: PACKET_AC_ACK_HASH.self,                    // 0x1dc

    PACKET_HC_ACCEPT_ENTER_NEO_UNION.packetType: PACKET_HC_ACCEPT_ENTER_NEO_UNION.self, // 0x6b
    PACKET_HC_REFUSE_ENTER.packetType: PACKET_HC_REFUSE_ENTER.self,         // 0x6c
    PACKET_HC_ACCEPT_MAKECHAR.packetType: PACKET_HC_ACCEPT_MAKECHAR.self,   // 0x6d
    PACKET_HC_REFUSE_MAKECHAR.packetType: PACKET_HC_REFUSE_MAKECHAR.self,   // 0x6e
    PACKET_HC_ACCEPT_DELETECHAR.packetType: PACKET_HC_ACCEPT_DELETECHAR.self,   // 0x6f
    PACKET_HC_REFUSE_DELETECHAR.packetType: PACKET_HC_REFUSE_DELETECHAR.self,   // 0x70
    PACKET_HC_NOTIFY_ZONESVR.packetType: PACKET_HC_NOTIFY_ZONESVR.self,         // 0x71, 0xac5
    PACKET_HC_BLOCK_CHARACTER.packetType: PACKET_HC_BLOCK_CHARACTER.self,       // 0x20d
    PACKET_HC_DELETE_CHAR_RESERVED.packetType: PACKET_HC_DELETE_CHAR_RESERVED.self, // 0x828
    PACKET_HC_DELETE_CHAR.packetType: PACKET_HC_DELETE_CHAR.self,                   // 0x82a
    PACKET_HC_DELETE_CHAR_CANCEL.packetType: PACKET_HC_DELETE_CHAR_CANCEL.self,     // 0x82c
    PACKET_HC_ACCEPT_ENTER_NEO_UNION_HEADER.packetType: PACKET_HC_ACCEPT_ENTER_NEO_UNION_HEADER.self,   // 0x82d
    HEADER_HC_NOTIFY_ACCESSIBLE_MAPNAME: PACKET_HC_NOTIFY_ACCESSIBLE_MAPNAME.self,  // 0x840
    PACKET_HC_SECOND_PASSWD_LOGIN.packetType: PACKET_HC_SECOND_PASSWD_LOGIN.self,   // 0x8b9
    PACKET_HC_CHARLIST_NOTIFY.packetType: PACKET_HC_CHARLIST_NOTIFY.self,           // 0x9a0

    HEADER_ZC_ACCEPT_ENTER: PACKET_ZC_ACCEPT_ENTER.self,            // 0x73, 0x2eb, 0xa18
    HEADER_ZC_REFUSE_ENTER: PACKET_ZC_REFUSE_ENTER.self,            // 0x74
    packet_header_idle_unitType: packet_idle_unit.self,             // 0x78, 0x1d8, 0x22a, 0x2ee, 0x7f9, 0x857, 0x915, 0x9dd, 0x9ff
    packet_header_spawn_unitType: packet_spawn_unit.self,           // 0x79, 0x1d9, 0x22b, 0x2ed, 0x7f8, 0x858, 0x90f, 0x9dc, 0x9fe
    packet_header_unit_walkingType: packet_unit_walking.self,       // 0x7b, 0x1da, 0x22c, 0x2ec, 0x7f7, 0x856, 0x914, 0x9db, 0x9fd
    HEADER_ZC_NOTIFY_TIME: PACKET_ZC_NOTIFY_TIME.self,              // 0x7f
    HEADER_ZC_NOTIFY_VANISH: PACKET_ZC_NOTIFY_VANISH.self,          // 0x80
    HEADER_ZC_NOTIFY_PLAYERMOVE: PACKET_ZC_NOTIFY_PLAYERMOVE.self,  // 0x87
    HEADER_ZC_STOPMOVE: PACKET_ZC_STOPMOVE.self,                    // 0x88
    HEADER_ZC_NOTIFY_ACT: PACKET_ZC_NOTIFY_ACT.self,                // 0x8a, 0x2e1, 0x8c8
    HEADER_ZC_NOTIFY_CHAT: PACKET_ZC_NOTIFY_CHAT.self,              // 0x8d
    HEADER_ZC_NOTIFY_PLAYERCHAT: PACKET_ZC_NOTIFY_PLAYERCHAT.self,  // 0x8e
    HEADER_ZC_NPCACK_MAPMOVE: PACKET_ZC_NPCACK_MAPMOVE.self,        // 0x91
    HEADER_ZC_NPCACK_SERVERMOVE: PACKET_ZC_NPCACK_SERVERMOVE.self,  // 0x92, 0xac7
    HEADER_ZC_ACK_REQNAMEALL: PACKET_ZC_ACK_REQNAMEALL.self,        // 0x95, 0x195, 0xa30
    HEADER_ZC_WHISPER: PACKET_ZC_WHISPER.self,                      // 0x97, 0x9de
    HEADER_ZC_ACK_WHISPER: PACKET_ZC_ACK_WHISPER.self,              // 0x98, 0x9df
    HEADER_ZC_BROADCAST: PACKET_ZC_BROADCAST.self,                  // 0x9a
    HEADER_ZC_CHANGE_DIRECTION: PACKET_ZC_CHANGE_DIRECTION.self,    // 0x9c
    HEADER_ZC_ITEM_ENTRY: PACKET_ZC_ITEM_ENTRY.self,                // 0x9d
    packet_header_dropflooritemType: packet_dropflooritem.self,     // 0x9e, 0x84b, 0xadd
    HEADER_ZC_ITEM_PICKUP_ACK: PACKET_ZC_ITEM_PICKUP_ACK.self,      // 0xa0, 0x29a, 0x2d4, 0x990, 0xa0c, 0xa37, 0xb41
    HEADER_ZC_ITEM_DISAPPEAR: PACKET_ZC_ITEM_DISAPPEAR.self,        // 0xa1
    packet_header_inventorylistnormalType: packet_itemlist_normal.self, // 0xa3, 0x1ee, 0x2e8, 0x991, 0xb09
    packet_header_inventorylistequipType: packet_itemlist_equip.self,   // 0xa4, 0x295, 0x2d0, 0x992, 0xa0d, 0xb0a, 0xb39
//    packet_header_storageListNormalType: ZC_STORE_ITEMLIST_NORMAL.self, // 0xa5, 0x295, 0x2ea, 0x995, 0xb09 (Duplicated)
//    packet_header_storageListEquipType: ZC_STORE_ITEMLIST_EQUIP.self,   // 0xa6, 0x296, 0x2d1, 0x996, 0xa10, 0xb0a, 0xb39 (Duplicated)
    packet_header_useItemAckType: PACKET_ZC_USE_ITEM_ACK.self,      // 0xa8, 0x1c8
    HEADER_ZC_REQ_WEAR_EQUIP_ACK: PACKET_ZC_REQ_WEAR_EQUIP_ACK.self,        // 0xaa, 0x8d0, 0x999
    HEADER_ZC_REQ_TAKEOFF_EQUIP_ACK: PACKET_ZC_REQ_TAKEOFF_EQUIP_ACK.self,  // 0xac, 0x8d1, 0x99a
    HEADER_ZC_ITEM_THROW_ACK: PACKET_ZC_ITEM_THROW_ACK.self,        // 0xaf
    HEADER_ZC_PAR_CHANGE: PACKET_ZC_PAR_CHANGE.self,                // 0xb0
    HEADER_ZC_LONGPAR_CHANGE: PACKET_ZC_LONGPAR_CHANGE.self,        // 0xb1
    HEADER_ZC_RESTART_ACK: PACKET_ZC_RESTART_ACK.self,              // 0xb3
    HEADER_ZC_SAY_DIALOG: PACKET_ZC_SAY_DIALOG.self,                // 0xb4
    HEADER_ZC_WAIT_DIALOG: PACKET_ZC_WAIT_DIALOG.self,              // 0xb5
    HEADER_ZC_CLOSE_DIALOG: PACKET_ZC_CLOSE_DIALOG.self,            // 0xb6
    HEADER_ZC_MENU_LIST: PACKET_ZC_MENU_LIST.self,                  // 0xb7
    HEADER_ZC_STATUS_CHANGE_ACK: PACKET_ZC_STATUS_CHANGE_ACK.self,  // 0xbc
    HEADER_ZC_STATUS: PACKET_ZC_STATUS.self,                        // 0xbd
    HEADER_ZC_STATUS_CHANGE: PACKET_ZC_STATUS_CHANGE.self,          // 0xbe
    HEADER_ZC_EMOTION: PACKET_ZC_EMOTION.self,                      // 0xc0
    HEADER_ZC_USER_COUNT: PACKET_ZC_USER_COUNT.self,                // 0xc2
    packet_header_sendLookType: PACKET_ZC_SPRITE_CHANGE.self,       // 0xc3, 0x1d7
    HEADER_ZC_SELECT_DEALTYPE: PACKET_ZC_SELECT_DEALTYPE.self,      // 0xc4
    HEADER_ZC_PC_PURCHASE_ITEMLIST: PACKET_ZC_PC_PURCHASE_ITEMLIST.self,    // 0xc6, 0xb77
    HEADER_ZC_PC_SELL_ITEMLIST: PACKET_ZC_PC_SELL_ITEMLIST.self,            // 0xc7
    HEADER_ZC_PC_PURCHASE_RESULT: PACKET_ZC_PC_PURCHASE_RESULT.self,        // 0xca
//    ZC_PC_SELL_RESULT,                                              // 0xcb
//    ZC_ACK_DISCONNECT_CHARACTER,                                    // 0xcd
    HEADER_ZC_SETTING_WHISPER_PC: PACKET_ZC_SETTING_WHISPER_PC.self,        // 0xd1
    HEADER_ZC_SETTING_WHISPER_STATE: PACKET_ZC_SETTING_WHISPER_STATE.self,  // 0xd2
    HEADER_ZC_WHISPER_LIST: PACKET_ZC_WHISPER_LIST.self,                    // 0xd4
    HEADER_ZC_ACK_CREATE_CHATROOM: PACKET_ZC_ACK_CREATE_CHATROOM.self,      // 0xd6
    HEADER_ZC_ROOM_NEWENTRY: PACKET_ZC_ROOM_NEWENTRY.self,          // 0xd7
    HEADER_ZC_DESTROY_ROOM: PACKET_ZC_DESTROY_ROOM.self,            // 0xd8
    HEADER_ZC_REFUSE_ENTER_ROOM: PACKET_ZC_REFUSE_ENTER_ROOM.self,  // 0xda
    HEADER_ZC_ENTER_ROOM: PACKET_ZC_ENTER_ROOM.self,                // 0xdb
    HEADER_ZC_MEMBER_NEWENTRY: PACKET_ZC_MEMBER_NEWENTRY.self,      // 0xdc
    HEADER_ZC_MEMBER_EXIT: PACKET_ZC_MEMBER_EXIT.self,              // 0xdd
    HEADER_ZC_CHANGE_CHATROOM: PACKET_ZC_CHANGE_CHATROOM.self,      // 0xdf
    HEADER_ZC_ROLE_CHANGE: PACKET_ZC_ROLE_CHANGE.self,              // 0xe1
    HEADER_ZC_REQ_EXCHANGE_ITEM: PACKET_ZC_REQ_EXCHANGE_ITEM.self,  // 0xe5, 0x1f4
    HEADER_ZC_ACK_EXCHANGE_ITEM: PACKET_ZC_ACK_EXCHANGE_ITEM.self,  // 0xe7, 0x1f5
    HEADER_ZC_ADD_EXCHANGE_ITEM: PACKET_ZC_ADD_EXCHANGE_ITEM.self,  // 0xe9, 0x80f, 0xa09, 0xa96, 0xb42
    HEADER_ZC_ACK_ADD_EXCHANGE_ITEM: PACKET_ZC_ACK_ADD_EXCHANGE_ITEM.self,      // 0xea
    HEADER_ZC_CONCLUDE_EXCHANGE_ITEM: PACKET_ZC_CONCLUDE_EXCHANGE_ITEM.self,    // 0xec
    HEADER_ZC_CANCEL_EXCHANGE_ITEM: PACKET_ZC_CANCEL_EXCHANGE_ITEM.self,        // 0xee
    HEADER_ZC_EXEC_EXCHANGE_ITEM: PACKET_ZC_EXEC_EXCHANGE_ITEM.self,            // 0xf0
    HEADER_ZC_EXCHANGEITEM_UNDO: PACKET_ZC_EXCHANGEITEM_UNDO.self,              // 0xf1
    HEADER_ZC_NOTIFY_STOREITEM_COUNTINFO: PACKET_ZC_NOTIFY_STOREITEM_COUNTINFO.self,    // 0xf2
    HEADER_ZC_ADD_ITEM_TO_STORE: PACKET_ZC_ADD_ITEM_TO_STORE.self,              // 0xf4, 0x1c4, 0xa0a, 0xb44
    HEADER_ZC_DELETE_ITEM_FROM_STORE: PACKET_ZC_DELETE_ITEM_FROM_STORE.self,    // 0xf6
    HEADER_ZC_CLOSE_STORE: PACKET_ZC_CLOSE_STORE.self,              // 0xf8
    HEADER_ZC_ACK_MAKE_GROUP: PACKET_ZC_ACK_MAKE_GROUP.self,        // 0xfa
    packet_header_partyinfo: PACKET_ZC_GROUP_LIST.self,             // 0xfb, 0xa44, 0xa5
    HEADER_ZC_PARTY_JOIN_REQ_ACK: PACKET_ZC_PARTY_JOIN_REQ_ACK.self,    // 0xfd, 0x2c5
    HEADER_ZC_PARTY_JOIN_REQ: PACKET_ZC_PARTY_JOIN_REQ.self,            // 0xfe, 0x2c6
//    ZC_REQ_GROUPINFO_CHANGE_V2,                                     // 0x101, 0x7d8
    packet_header_partymemberinfo: PACKET_ZC_ADD_MEMBER_TO_GROUP.self,              // 0x104, 0x1e9, 0xa43, 0xae4
    HEADER_ZC_DELETE_MEMBER_FROM_GROUP: PACKET_ZC_DELETE_MEMBER_FROM_GROUP.self,    // 0x105
    HEADER_ZC_NOTIFY_HP_TO_GROUPM: PACKET_ZC_NOTIFY_HP_TO_GROUPM.self,  // 0x106, 0x80e, 0xbab
    HEADER_ZC_NOTIFY_POSITION_TO_GROUPM: PACKET_ZC_NOTIFY_POSITION_TO_GROUPM.self,  // 0x107
    HEADER_ZC_NOTIFY_CHAT_PARTY: PACKET_ZC_NOTIFY_CHAT_PARTY.self,  // 0x109
    HEADER_ZC_MVP_GETTING_ITEM: PACKET_ZC_MVP_GETTING_ITEM.self,    // 0x10a
    HEADER_ZC_MVP_GETTING_SPECIAL_EXP: PACKET_ZC_MVP_GETTING_SPECIAL_EXP.self,  // 0x10b
    HEADER_ZC_MVP: PACKET_ZC_MVP.self,                              // 0x10c
    HEADER_ZC_THROW_MVPITEM: PACKET_ZC_THROW_MVPITEM.self,          // 0x10d
    HEADER_ZC_SKILLINFO_UPDATE: PACKET_ZC_SKILLINFO_UPDATE.self,    // 0x10e
    HEADER_ZC_SKILLINFO_LIST: PACKET_ZC_SKILLINFO_LIST.self,        // 0x10f, 0xb32
    HEADER_ZC_ACK_TOUSESKILL: PACKET_ZC_ACK_TOUSESKILL.self,        // 0x110
    HEADER_ZC_ADD_SKILL: PACKET_ZC_ADD_SKILL.self,                  // 0x111, 0xb31
    HEADER_ZC_NOTIFY_SKILL: PACKET_ZC_NOTIFY_SKILL.self,                    // 0x114, 0x1de
    HEADER_ZC_NOTIFY_SKILL_POSITION: PACKET_ZC_NOTIFY_SKILL_POSITION.self,  // 0x115
    HEADER_ZC_NOTIFY_GROUNDSKILL: PACKET_ZC_NOTIFY_GROUNDSKILL.self,        // 0x117
    HEADER_ZC_STATE_CHANGE: PACKET_ZC_STATE_CHANGE.self,            // 0x119, 0x229
    HEADER_ZC_USE_SKILL: PACKET_ZC_USE_SKILL.self,                  // 0x11a, 0x9cb
    HEADER_ZC_WARPLIST: PACKET_ZC_WARPLIST.self,                    // 0x11c, 0xabe
    HEADER_ZC_ACK_REMEMBER_WARPPOINT: PACKET_ZC_ACK_REMEMBER_WARPPOINT.self,    // 0x11e
//    ZC_SKILL_ENTRY,                                                 // 0x11f
    HEADER_ZC_SKILL_DISAPPEAR: PACKET_ZC_SKILL_DISAPPEAR.self,      // 0x120
    HEADER_ZC_NOTIFY_CARTITEM_COUNTINFO: PACKET_ZC_NOTIFY_CARTITEM_COUNTINFO.self,  // 0x121
//    packet_header_cartlistequipType: packet_itemlist_equip.self,    // 0x122, 0x297, 0x2d2, 0x994, 0xa0f, 0xb0a, 0xb39 (Duplicated)
//    packet_header_cartlistnormalType: packet_itemlist_normal.self,  // 0x123, 0x1ef, 0x2e9, 0x993, 0xb09 (Duplicated)
    HEADER_ZC_ADD_ITEM_TO_CART: PACKET_ZC_ADD_ITEM_TO_CART.self,            // 0x124, 0x1c5, 0xa0b, 0xb45
    HEADER_ZC_DELETE_ITEM_FROM_CART: PACKET_ZC_DELETE_ITEM_FROM_CART.self,  // 0x125
    HEADER_ZC_CARTOFF: PACKET_ZC_CARTOFF.self,                              // 0x12b
    HEADER_ZC_ACK_ADDITEM_TO_CART: PACKET_ZC_ACK_ADDITEM_TO_CART.self,      // 0x12c
    HEADER_ZC_OPENSTORE: PACKET_ZC_OPENSTORE.self,                  // 0x12d
    HEADER_ZC_STORE_ENTRY: PACKET_ZC_STORE_ENTRY.self,              // 0x131
    HEADER_ZC_DISAPPEAR_ENTRY: PACKET_ZC_DISAPPEAR_ENTRY.self,      // 0x132
    HEADER_ZC_PC_PURCHASE_ITEMLIST_FROMMC: PACKET_ZC_PC_PURCHASE_ITEMLIST_FROMMC.self,  // 0x133, 0x800, 0xb3d
    HEADER_ZC_PC_PURCHASE_RESULT_FROMMC: PACKET_ZC_PC_PURCHASE_RESULT_FROMMC.self,      // 0x135
    HEADER_ZC_PC_PURCHASE_MYITEMLIST: PACKET_ZC_PC_PURCHASE_MYITEMLIST.self,    // 0x136, 0xb40
    HEADER_ZC_DELETEITEM_FROM_MCSTORE: PACKET_ZC_DELETEITEM_FROM_MCSTORE.self,  // 0x137, 0x9e5
    HEADER_ZC_ATTACK_FAILURE_FOR_DISTANCE: PACKET_ZC_ATTACK_FAILURE_FOR_DISTANCE.self,  // 0x139
    HEADER_ZC_ATTACK_RANGE: PACKET_ZC_ATTACK_RANGE.self,            // 0x13a
    HEADER_ZC_ACTION_FAILURE: PACKET_ZC_ACTION_FAILURE.self,        // 0x13b
    HEADER_ZC_EQUIP_ARROW: PACKET_ZC_EQUIP_ARROW.self,              // 0x13c
    HEADER_ZC_RECOVERY: PACKET_ZC_RECOVERY.self,                    // 0x13d, 0xa27
    HEADER_ZC_USESKILL_ACK: PACKET_ZC_USESKILL_ACK.self,            // 0x13e, 0x7fb, 0xb1a
    HEADER_ZC_COUPLESTATUS: PACKET_ZC_COUPLESTATUS.self,            // 0x141
    HEADER_ZC_OPEN_EDITDLG: PACKET_ZC_OPEN_EDITDLG.self,            // 0x142
    HEADER_ZC_COMPASS: PACKET_ZC_COMPASS.self,                      // 0x144
    HEADER_ZC_SHOW_IMAGE: PACKET_ZC_SHOW_IMAGE.self,                // 0x145, 0x1b3
    HEADER_ZC_AUTORUN_SKILL: PACKET_ZC_AUTORUN_SKILL.self,          // 0x147
    HEADER_ZC_RESURRECTION: PACKET_ZC_RESURRECTION.self,            // 0x148
//    ZC_ACK_GIVE_MANNER_POINT,                                       // 0x14a
    HEADER_ZC_NOTIFY_MANNER_POINT_GIVEN: PACKET_ZC_NOTIFY_MANNER_POINT_GIVEN.self,  // 0x14b
    HEADER_ZC_MYGUILD_BASIC_INFO: PACKET_ZC_MYGUILD_BASIC_INFO.self,            // 0x14c
    HEADER_ZC_ACK_GUILD_MENUINTERFACE: PACKET_ZC_ACK_GUILD_MENUINTERFACE.self,  // 0x14e
    HEADER_ZC_GUILD_INFO: PACKET_ZC_GUILD_INFO.self,                // 0x150, 0x1b6, 0xa84, 0xb7b
    HEADER_ZC_GUILD_EMBLEM_IMG: PACKET_ZC_GUILD_EMBLEM_IMG.self,    // 0x152, 0xb36
    HEADER_ZC_MEMBERMGR_INFO: PACKET_ZC_MEMBERMGR_INFO.self,        // 0x154, 0xaa5, 0xb7d
//    ZC_ACK_REQ_CHANGE_MEMBERS,                                      // 0x156
    packet_header_guildLeave: PACKET_ZC_ACK_LEAVE_GUILD2.self,      // 0x15a, 0xa83
    packet_header_guildExpulsion: PACKET_ZC_ACK_BAN_GUILD3.self,    // 0x15c, 0x839, 0xa82
    HEADER_ZC_ACK_DISORGANIZE_GUILD_RESULT: PACKET_ZC_ACK_DISORGANIZE_GUILD_RESULT.self,    // 0x15e
    HEADER_ZC_POSITION_INFO: PACKET_ZC_POSITION_INFO.self,          // 0x160
    HEADER_ZC_GUILD_SKILLINFO: PACKET_ZC_GUILD_SKILLINFO.self,      // 0x162
    HEADER_ZC_BAN_LIST: PACKET_ZC_BAN_LIST.self,                    // 0x163, 0xa87, 0x0b7c
    HEADER_ZC_POSITION_ID_NAME_INFO: PACKET_ZC_POSITION_ID_NAME_INFO.self,  // 0x166
    HEADER_ZC_RESULT_MAKE_GUILD: PACKET_ZC_RESULT_MAKE_GUILD.self,      // 0x167
    HEADER_ZC_ACK_REQ_JOIN_GUILD: PACKET_ZC_ACK_REQ_JOIN_GUILD.self,    // 0x169
    HEADER_ZC_REQ_JOIN_GUILD: PACKET_ZC_REQ_JOIN_GUILD.self,            // 0x16a
    HEADER_ZC_UPDATE_GDID: PACKET_ZC_UPDATE_GDID.self,                  // 0x16c
//    ZC_UPDATE_CHARSTAT,                                             // 0x16d, 0x1f2
    HEADER_ZC_GUILD_NOTICE: PACKET_ZC_GUILD_NOTICE.self,                // 0x16f
    HEADER_ZC_REQ_ALLY_GUILD: PACKET_ZC_REQ_ALLY_GUILD.self,            // 0x171
    HEADER_ZC_ACK_REQ_ALLY_GUILD: PACKET_ZC_ACK_REQ_ALLY_GUILD.self,    // 0x173
//    ZC_ACK_CHANGE_GUILD_POSITIONINFO,                                   // 0x174
//    ZC_ITEMIDENTIFY_LIST,                                           // 0x177
    HEADER_ZC_ACK_ITEMIDENTIFY: PACKET_ZC_ACK_ITEMIDENTIFY.self,    // 0x179
//    ZC_ITEMCOMPOSITION_LIST,                                        // 0x17b
    HEADER_ZC_ACK_ITEMCOMPOSITION: PACKET_ZC_ACK_ITEMCOMPOSITION.self,  // 0x17d
    HEADER_ZC_GUILD_CHAT: PACKET_ZC_GUILD_CHAT.self,                // 0x17f
    HEADER_ZC_ACK_REQ_HOSTILE_GUILD: PACKET_ZC_ACK_REQ_HOSTILE_GUILD.self,  // 0x181
    HEADER_ZC_DELETE_RELATED_GUILD: PACKET_ZC_DELETE_RELATED_GUILD.self,    // 0x184
//    ZC_ADD_RELATED_GUILD,                                           // 0x185
    HEADER_ZC_ACK_ITEMREFINING: PACKET_ZC_ACK_ITEMREFINING.self,    // 0x188
    HEADER_ZC_NOTIFY_MAPINFO: PACKET_ZC_NOTIFY_MAPINFO.self,        // 0x189
//    ZC_ACK_REQ_DISCONNECT,                                          // 0x18b
    HEADER_ZC_MONSTER_INFO: PACKET_ZC_MONSTER_INFO.self,            // 0x18c
    HEADER_ZC_MAKABLEITEMLIST: PACKET_ZC_MAKABLEITEMLIST.self,      // 0x18d
    HEADER_ZC_ACK_REQMAKINGITEM: PACKET_ZC_ACK_REQMAKINGITEM.self,  // 0x18f
    HEADER_ZC_TALKBOX_CHATCONTENTS: PACKET_ZC_TALKBOX_CHATCONTENTS.self,    // 0x191
    HEADER_ZC_UPDATE_MAPINFO: PACKET_ZC_UPDATE_MAPINFO.self,        // 0x192
    HEADER_ZC_ACK_REQNAME_BYGID: PACKET_ZC_ACK_REQNAME_BYGID.self,  // 0x194, 0xaf7
//    ZC_MSG_STATE_CHANGE,                                            // 0x196, 0x43f, 0x983
    packet_header_maptypeproperty2Type: PACKET_ZC_MAPPROPERTY_R2.self,  // 0x199, 0x99b
//    ZC_NOTIFY_RANKING,                                              // 0x19a
    HEADER_ZC_NOTIFY_EFFECT: PACKET_ZC_NOTIFY_EFFECT.self,          // 0x19b
    HEADER_ZC_START_CAPTURE: PACKET_ZC_START_CAPTURE.self,              // 0x19e
    HEADER_ZC_TRYCAPTURE_MONSTER: PACKET_ZC_TRYCAPTURE_MONSTER.self,    // 0x1a0
    HEADER_ZC_PROPERTY_PET: PACKET_ZC_PROPERTY_PET.self,                // 0x1a2
    HEADER_ZC_FEED_PET: PACKET_ZC_FEED_PET.self,                        // 0x1a3
    HEADER_ZC_CHANGESTATE_PET: PACKET_ZC_CHANGESTATE_PET.self,          // 0x1a4
//    ZC_PETEGG_LIST,                                                     // 0x1a6
    HEADER_ZC_PET_ACT: PACKET_ZC_PET_ACT.self,                          // 0x1aa
    HEADER_ZC_PAR_CHANGE_USER: PACKET_ZC_PAR_CHANGE_USER.self,      // 0x1ab
    HEADER_ZC_SKILL_UPDATE: PACKET_ZC_SKILL_UPDATE.self,            // 0x1ac
    HEADER_ZC_MAKINGARROW_LIST: PACKET_ZC_MAKINGARROW_LIST.self,    // 0x1ad
    HEADER_ZC_NPCSPRITE_CHANGE: PACKET_ZC_NPCSPRITE_CHANGE.self,    // 0x1b0
//    ZC_SHOWDIGIT,                                                   // 0x1b1
    HEADER_ZC_CHANGE_GUILD: PACKET_ZC_CHANGE_GUILD.self,            // 0x1b4, 0xb1f, 0xb47
    HEADER_ZC_DISPEL: PACKET_ZC_DISPEL.self,                        // 0x1b9
    HEADER_ZC_BROADCAST2: PACKET_ZC_BROADCAST2.self,                // 0x1c3
    packet_header_graffiti_entryType: packet_graffiti_entry.self,   // 0x1c9
    HEADER_ZC_AUTOSPELLLIST: PACKET_ZC_AUTOSPELLLIST.self,          // 0x1cd, 0xafb
//    ZC_DEVOTIONLIST,                                                // 0x1cf
    HEADER_ZC_SPIRITS: PACKET_ZC_SPIRITS.self,                      // 0x1d0
    HEADER_ZC_BLADESTOP: PACKET_ZC_BLADESTOP.self,                  // 0x1d1
    HEADER_ZC_COMBODELAY: PACKET_ZC_COMBODELAY.self,                // 0x1d2
    HEADER_ZC_SOUND: PACKET_ZC_SOUND.self,                          // 0x1d3
    HEADER_ZC_OPEN_EDITDLGSTR: PACKET_ZC_OPEN_EDITDLGSTR.self,      // 0x1d4
    HEADER_ZC_NOTIFY_MAPPROPERTY2: PACKET_ZC_NOTIFY_MAPPROPERTY2.self,  // 0x1d6
//    ZC_ACK_ACCOUNTNAME,                                             // 0x1e0
    HEADER_ZC_SPIRITS2: PACKET_ZC_SPIRITS2.self,                    // 0x1e1
//    ZC_REQ_COUPLE,                                                  // 0x1e2
//    ZC_START_COUPLE,                                                // 0x1e4
    HEADER_ZC_COUPLENAME: PACKET_ZC_COUPLENAME.self,                // 0x1e6
    HEADER_ZC_CONGRATULATION: PACKET_ZC_CONGRATULATION.self,        // 0x1ea
    HEADER_ZC_NOTIFY_POSITION_TO_GUILDM: PACKET_ZC_NOTIFY_POSITION_TO_GUILDM.self,  // 0x1eb
//    ZC_NOTIFY_EFFECT2,                                              // 0x1f3
//    ZC_REQ_BABY,                                                    // 0x1f6
    HEADER_ZC_REPAIRITEMLIST: PACKET_ZC_REPAIRITEMLIST.self,        // 0x1fc, 0xb65
    HEADER_ZC_ACK_ITEMREPAIR: PACKET_ZC_ACK_ITEMREPAIR.self,        // 0x1fe
    HEADER_ZC_HIGHJUMP: PACKET_ZC_HIGHJUMP.self,                    // 0x1ff
    HEADER_ZC_FRIENDS_LIST: PACKET_ZC_FRIENDS_LIST.self,            // 0x201
    HEADER_ZC_DIVORCE: PACKET_ZC_DIVORCE.self,                      // 0x205
    HEADER_ZC_FRIENDS_STATE: PACKET_ZC_FRIENDS_STATE.self,          // 0x206
//    ZC_REQ_ADD_FRIENDS,                                             // 0x207
//    ZC_ADD_FRIENDS_LIST,                                            // 0x209
//    ZC_DELETE_FRIENDS,                                              // 0x20a
//    ZC_STARSKILL,                                                   // 0x20e
//    ZC_ACK_PVPPOINT,                                                // 0x210
//    ZC_ACK_STATUS_GM,                                               // 0x214
    HEADER_ZC_SKILLMSG: PACKET_ZC_SKILLMSG.self,                    // 0x215
//    ZC_BABYMSG,                                                     // 0x216
    HEADER_ZC_BLACKSMITH_RANK: PACKET_ZC_BLACKSMITH_RANK.self,      // 0x219
    HEADER_ZC_ALCHEMIST_RANK: PACKET_ZC_ALCHEMIST_RANK.self,        // 0x21a
    HEADER_ZC_BLACKSMITH_POINT: PACKET_ZC_BLACKSMITH_POINT.self,    // 0x21b
    HEADER_ZC_ALCHEMIST_POINT: PACKET_ZC_ALCHEMIST_POINT.self,      // 0x21c
    HEADER_ZC_NOTIFY_WEAPONITEMLIST: PACKET_ZC_NOTIFY_WEAPONITEMLIST.self,  // 0x221
    HEADER_ZC_ACK_WEAPONREFINE: PACKET_ZC_ACK_WEAPONREFINE.self,    // 0x223
    HEADER_ZC_TAEKWON_POINT: PACKET_ZC_TAEKWON_POINT.self,          // 0x224
    HEADER_ZC_TAEKWON_RANK: PACKET_ZC_TAEKWON_RANK.self,            // 0x226
    HEADER_ZC_PROPERTY_HOMUN: PACKET_ZC_PROPERTY_HOMUN.self,        // 0x22e, 0x9f7, 0xb2f, 0xb76, 0xba4
    HEADER_ZC_FEED_MER: PACKET_ZC_FEED_MER.self,                    // 0x22f
    HEADER_ZC_CHANGESTATE_MER: PACKET_ZC_CHANGESTATE_MER.self,      // 0x230
//    ZC_REQ_STORE_PASSWORD,                                          // 0x23a
//    ZC_RESULT_STORE_PASSWORD,                                       // 0x23c
//    ZC_MAIL_REQ_GET_LIST,                                           // 0x240, 0x9f0, 0xa7d, 0xac2
//    ZC_MAIL_REQ_OPEN,                                               // 0x242
//    ZC_MAIL_REQ_GET_ITEM,                                           // 0x245
//    ZC_MAIL_REQ_SEND,                                               // 0x249
    HEADER_ZC_MAIL_RECEIVE: PACKET_ZC_MAIL_RECEIVE.self,            // 0x24a
//    ZC_AUCTION_RESULT,                                              // 0x250
//    ZC_AUCTION_ITEM_REQ_SEARCH,                                     // 0x252
//    ZC_STARPLACE,                                                   // 0x253
//    ZC_ACK_MAIL_ADD_ITEM,                                           // 0x255
//    ZC_ACK_AUCTION_ADD_ITEM,                                        // 0x256
//    ZC_ACK_MAIL_DELETE,                                             // 0x257
    HEADER_ZC_MAKINGITEM_LIST: PACKET_ZC_MAKINGITEM_LIST.self,      // 0x25a
//    ZC_AUCTION_ACK_MY_SELL_STOP,                                    // 0x25e
//    ZC_AUCTION_WINDOWS,                                             // 0x25f
//    ZC_MAIL_WINDOWS,                                                // 0x260
//    ZC_ACK_MAIL_RETURN,                                             // 0x274
    HEADER_ZC_AID: PACKET_ZC_AID.self,                              // 0x283
    HEADER_ZC_NOTIFY_EFFECT3: PACKET_ZC_NOTIFY_EFFECT3.self,        // 0x284, 0xb69
    HEADER_ZC_PC_CASH_POINT_ITEMLIST: PACKET_ZC_PC_CASH_POINT_ITEMLIST.self,    // 0x287
//    ZC_PC_CASH_POINT_UPDATE,                                        // 0x289
    HEADER_ZC_NPC_SHOWEFST_UPDATE: PACKET_ZC_NPC_SHOWEFST_UPDATE.self,  // 0x28a
    HEADER_ZC_MSG: PACKET_ZC_MSG.self,                              // 0x291
    HEADER_ZC_BOSS_INFO: PACKET_ZC_BOSS_INFO.self,                  // 0x293
//    ZC_READ_BOOK,                                                   // 0x294
    HEADER_ZC_CASH_TIME_COUNTER: PACKET_ZC_CASH_TIME_COUNTER.self,  // 0x298
    HEADER_ZC_CASH_ITEM_DELETE: PACKET_ZC_CASH_ITEM_DELETE.self,    // 0x299
//    ZC_MER_INIT,                                                    // 0x29b
//    ZC_MER_SKILLINFO_LIST,                                          // 0x29d
//    ZC_MER_PAR_CHANGE,                                              // 0x2a2
//    packet_header_questListType: ZC_ALL_QUEST_LIST,                 // 0x2b1, 0x97a, 0x9f8, 0xaff
//    ZC_ALL_QUEST_MISSION,                                           // 0x2b2
//    ZC_ADD_QUEST,                                                   // 0x2b3, 0x9f9
//    ZC_DEL_QUEST,                                                   // 0x2b4
//    ZC_UPDATE_MISSION_HUNT,                                         // 0x2b5, 0x9fa
//    ZC_ACTIVE_QUEST,                                                // 0x2b7
    HEADER_ZC_ITEM_PICKUP_PARTY: PACKET_ZC_ITEM_PICKUP_PARTY.self,  // 0x2b8, 0xb67
    HEADER_ZC_SHORTCUT_KEY_LIST: PACKET_ZC_SHORTCUT_KEY_LIST.self,  // 0x2b9, 0x7d9, 0xa00, 0xb20
    HEADER_ZC_EQUIPITEM_DAMAGED: PACKET_ZC_EQUIPITEM_DAMAGED.self,  // 0x2bb
    HEADER_ZC_NPC_CHAT: PACKET_ZC_NPC_CHAT.self,                    // 0x2c1
    0x2c2: PACKET_ZC_FORMATSTRING_MSG.self,
    HEADER_ZC_PARTY_CONFIG: PACKET_ZC_PARTY_CONFIG.self,            // 0x2c9
//    ZC_MEMORIALDUNGEON_SUBSCRIPTION_INFO,                           // 0x2cb
//    ZC_MEMORIALDUNGEON_SUBSCRIPTION_NOTIFY,                         // 0x2cc
//    ZC_MEMORIALDUNGEON_INFO,                                        // 0x2cd
//    ZC_MEMORIALDUNGEON_NOTIFY,                                      // 0x2ce
    HEADER_ZC_NOTIFY_BIND_ON_EQUIP: PACKET_ZC_NOTIFY_BIND_ON_EQUIP.self,    // 0x2d3
    HEADER_ZC_EQUIPWIN_MICROSCOPE: PACKET_ZC_EQUIPWIN_MICROSCOPE.self,  // 0x2d7, 0x859, 0x906, 0x997, 0xa2d, 0xb03, 0xb37
    HEADER_ZC_CONFIG: PACKET_ZC_CONFIG.self,                        // 0x2d9
    HEADER_ZC_CONFIG_NOTIFY: PACKET_ZC_CONFIG_NOTIFY.self,          // 0x2da
//    ZC_BATTLEFIELD_CHAT,                                            // 0x2dc
//    ZC_BATTLEFIELD_NOTIFY_CAMPINFO,                                 // 0x2dd
//    ZC_BATTLEFIELD_NOTIFY_POINT,                                    // 0x2de
//    ZC_BATTLEFIELD_NOTIFY_POSITION,                                 // 0x2df
    HEADER_ZC_BATTLEFIELD_NOTIFY_HP: PACKET_ZC_BATTLEFIELD_NOTIFY_HP.self,  // 0x2e0, 0xa0e, 0xbaa
//    ZC_NOTIFY_FONT,                                                 // 0x2ef
//    ZC_PROGRESS,                                                    // 0x2f0
//    ZC_PROGRESS_CANCEL,                                             // 0x2f2
    HEADER_ZC_SKILL_POSTDELAY: PACKET_ZC_SKILL_POSTDELAY.self,      // 0x43d
    HEADER_ZC_MILLENNIUMSHIELD: PACKET_ZC_MILLENNIUMSHIELD.self,    // 0x440
    HEADER_ZC_SKILLINFO_DELETE: PACKET_ZC_SKILLINFO_DELETE.self,    // 0x441
    HEADER_ZC_SKILL_SELECT_REQUEST: PACKET_ZC_SKILL_SELECT_REQUEST.self,    // 0x442
    HEADER_ZC_QUEST_NOTIFY_EFFECT: PACKET_ZC_QUEST_NOTIFY_EFFECT.self,  // 0x446
    HEADER_ZC_HO_PAR_CHANGE: PACKET_ZC_HO_PAR_CHANGE.self,          // 0x7db, 0xba5
    HEADER_ZC_SKILLINFO_UPDATE2: PACKET_ZC_SKILLINFO_UPDATE2.self,  // 0x7e1, 0xb33
    HEADER_ZC_MSG_VALUE: PACKET_ZC_MSG_VALUE.self,                  // 0x7e2
//    ZC_ITEMLISTWIN_OPEN,                                            // 0x7e3
    HEADER_ZC_MSG_SKILL: PACKET_ZC_MSG_SKILL.self,                  // 0x7e6
//    ZC_NOTIFY_EXP,                                                  // 0x7f6, 0xacc
    HEADER_ZC_DELETE_ITEM_FROM_BODY: PACKET_ZC_DELETE_ITEM_FROM_BODY.self,  // 0x7fa
//    ZC_CHANGE_GROUP_MASTER,                                         // 0x7fc
    HEADER_ZC_PLAY_NPC_BGM: PACKET_ZC_PLAY_NPC_BGM.self,            // 0x7fe
//    ZC_PARTY_BOOKING_ACK_REGISTER,                                  // 0x803
//    ZC_PARTY_BOOKING_ACK_SEARCH,                                    // 0x805
//    ZC_PARTY_BOOKING_ACK_DELETE,                                    // 0x807
//    ZC_PARTY_BOOKING_NOTIFY_INSERT,                                 // 0x809
//    ZC_PARTY_BOOKING_NOTIFY_UPDATE,                                 // 0x80a
//    ZC_PARTY_BOOKING_NOTIFY_DELETE,                                 // 0x80b
//    ZC_OPEN_BUYING_STORE,                                           // 0x810
//    ZC_FAILED_OPEN_BUYING_STORE_TO_BUYER,                           // 0x812
    HEADER_ZC_MYITEMLIST_BUYING_STORE: PACKET_ZC_MYITEMLIST_BUYING_STORE.self,              // 0x813
    HEADER_ZC_BUYING_STORE_ENTRY: PACKET_ZC_BUYING_STORE_ENTRY.self,                        // 0x814
    HEADER_ZC_DISAPPEAR_BUYING_STORE_ENTRY: PACKET_ZC_DISAPPEAR_BUYING_STORE_ENTRY.self,    // 0x816
    HEADER_ZC_ACK_ITEMLIST_BUYING_STORE: PACKET_ZC_ACK_ITEMLIST_BUYING_STORE.self,          // 0x818
//    ZC_FAILED_TRADE_BUYING_STORE_TO_BUYER,                          // 0x81a
    packet_header_buyingStoreUpdateItemType: PACKET_ZC_UPDATE_ITEM_FROM_BUYING_STORE.self,  // 0x81b, 0x9e6
//    ZC_ITEM_DELETE_BUYING_STORE,                                    // 0x81c
//    ZC_EL_INIT,                                                     // 0x81d
    HEADER_ZC_EL_PAR_CHANGE: PACKET_ZC_EL_PAR_CHANGE.self,          // 0x81e
    HEADER_ZC_FAILED_TRADE_BUYING_STORE_TO_SELLER: PACKET_ZC_FAILED_TRADE_BUYING_STORE_TO_SELLER.self,  // 0x824
    HEADER_ZC_SEARCH_STORE_INFO_ACK: PACKET_ZC_SEARCH_STORE_INFO_ACK.self,          // 0x836, 0xb64
    HEADER_ZC_SEARCH_STORE_INFO_FAILED: PACKET_ZC_SEARCH_STORE_INFO_FAILED.self,    // 0x837

    HEADER_ZC_LONGLONGPAR_CHANGE: PACKET_ZC_LONGLONGPAR_CHANGE.self,
    HEADER_ZC_BROADCASTING_SPECIAL_ITEM_OBTAIN_item: PACKET_ZC_BROADCASTING_SPECIAL_ITEM_OBTAIN_item.self,
    HEADER_ZC_INVENTORY_START: PACKET_ZC_INVENTORY_START.self,
    HEADER_ZC_INVENTORY_END: PACKET_ZC_INVENTORY_END.self,
    HEADER_ZC_NPC_MARKET_OPEN: PACKET_ZC_NPC_MARKET_OPEN.self,
    HEADER_ZC_CHECKNAME: PACKET_ZC_CHECKNAME.self,
    HEADER_ZC_ACK_READ_RODEX: PACKET_ZC_ACK_READ_RODEX.self,
    HEADER_ZC_CLANINFO: PACKET_ZC_CLANINFO.self,
    HEADER_ZC_UI_OPEN: PACKET_ZC_UI_OPEN.self,
    HEADER_ZC_UI_OPEN2: PACKET_ZC_UI_OPEN2.self,
    HEADER_ZC_OPEN_SEARCH_STORE_INFO: PACKET_ZC_OPEN_SEARCH_STORE_INFO.self,
    HEADER_ZC_SSILIST_ITEM_CLICK_ACK: PACKET_ZC_SSILIST_ITEM_CLICK_ACK.self,
    HEADER_ZC_ACK_REQNAMEALL_NPC: PACKET_ZC_ACK_REQNAMEALL_NPC.self,
    HEADER_ZC_MOVE_ITEM_FAILED: PACKET_ZC_MOVE_ITEM_FAILED.self,
    HEADER_ZC_VIEW_CAMERAINFO: PACKET_ZC_VIEW_CAMERAINFO.self,
    HEADER_ZC_CHANGE_ITEM_OPTION: PACKET_ZC_CHANGE_ITEM_OPTION.self,
    HEADER_ZC_UPDATE_CARDSLOT: PACKET_ZC_UPDATE_CARDSLOT.self,
    HEADER_ZC_DEBUGMSG: PACKET_ZC_DEBUGMSG.self,
    HEADER_ZC_EXTEND_BODYITEM_SIZE: PACKET_ZC_EXTEND_BODYITEM_SIZE.self,
    HEADER_ZC_ACK_OPEN_MSGBOX_EXTEND_BODYITEM_SIZE: PACKET_ZC_ACK_OPEN_MSGBOX_EXTEND_BODYITEM_SIZE.self,
    HEADER_ZC_ACK_EXTEND_BODYITEM_SIZE: PACKET_ZC_ACK_EXTEND_BODYITEM_SIZE.self,
    HEADER_ZC_NPC_BARTER_MARKET_ITEMINFO: PACKET_ZC_NPC_BARTER_MARKET_ITEMINFO.self,
    HEADER_ZC_PING_LIVE: PACKET_ZC_PING_LIVE.self,
    HEADER_ZC_NOTIFY_ACTORINIT: PACKET_ZC_NOTIFY_ACTORINIT.self,
    HEADER_ZC_ACK_CLOSE_ROULETTE: PACKET_ZC_ACK_CLOSE_ROULETTE.self,
    HEADER_ZC_ACK_MERGE_ITEM: PACKET_ZC_ACK_MERGE_ITEM.self,
    HEADER_ZC_MERGE_ITEM_OPEN: PACKET_ZC_MERGE_ITEM_OPEN.self,
    HEADER_ZC_SE_PC_BUY_CASHITEM_RESULT: PACKET_ZC_SE_PC_BUY_CASHITEM_RESULT.self,
    HEADER_ZC_OPEN_REFINING_UI: PACKET_ZC_OPEN_REFINING_UI.self,
    HEADER_ZC_REFINING_MATERIAL_LIST: PACKET_ZC_REFINING_MATERIAL_LIST.self,
    HEADER_ZC_BROADCAST_ITEMREFINING_RESULT: PACKET_ZC_BROADCAST_ITEMREFINING_RESULT.self,
    HEADER_ZC_EQUIPMENT_EFFECT: PACKET_ZC_EQUIPMENT_EFFECT.self,
    HEADER_ZC_NPC_MARKET_PURCHASE_RESULT: PACKET_ZC_NPC_MARKET_PURCHASE_RESULT.self,
    HEADER_ZC_GUILD_AGIT_INFO: PACKET_ZC_GUILD_AGIT_INFO.self,
    HEADER_ZC_REQ_ACK_MOVE_GUILD_AGIT: PACKET_ZC_REQ_ACK_MOVE_GUILD_AGIT.self,
    HEADER_ZC_REQ_ACK_AGIT_INVESTMENT: PACKET_ZC_REQ_ACK_AGIT_INVESTMENT.self,
    HEADER_ZC_RANDOM_COMBINE_ITEM_UI_OPEN: PACKET_ZC_RANDOM_COMBINE_ITEM_UI_OPEN.self,
    HEADER_ZC_ACK_RANDOM_COMBINE_ITEM: PACKET_ZC_ACK_RANDOM_COMBINE_ITEM.self,
    HEADER_ZC_SE_CASHSHOP_OPEN: PACKET_ZC_SE_CASHSHOP_OPEN.self,
    HEADER_ZC_NPC_EXPANDED_BARTER_MARKET_ITEMINFO: PACKET_ZC_NPC_EXPANDED_BARTER_MARKET_ITEMINFO.self,
    HEADER_ZC_RANDOM_UPGRADE_ITEM_UI_OPEN: PACKET_ZC_RANDOM_UPGRADE_ITEM_UI_OPEN.self,
    HEADER_ZC_ACK_RANDOM_UPGRADE_ITEM: PACKET_ZC_ACK_RANDOM_UPGRADE_ITEM.self,
    HEADER_ZC_PERSONAL_INFOMATION: PACKET_ZC_PERSONAL_INFOMATION.self,
    HEADER_ZC_C_MARKERINFO: PACKET_ZC_C_MARKERINFO.self,
    HEADER_ZC_ACK_UPLOAD_MACRO_DETECTOR: PACKET_ZC_ACK_UPLOAD_MACRO_DETECTOR.self,
    HEADER_ZC_COMPLETE_UPLOAD_MACRO_DETECTOR_CAPTCHA: PACKET_ZC_COMPLETE_UPLOAD_MACRO_DETECTOR_CAPTCHA.self,
    HEADER_ZC_ACK_APPLY_MACRO_DETECTOR: PACKET_ZC_ACK_APPLY_MACRO_DETECTOR.self,
    HEADER_ZC_APPLY_MACRO_DETECTOR: PACKET_ZC_APPLY_MACRO_DETECTOR.self,
    HEADER_ZC_APPLY_MACRO_DETECTOR_CAPTCHA: PACKET_ZC_APPLY_MACRO_DETECTOR_CAPTCHA.self,
    HEADER_ZC_REQ_ANSWER_MACRO_DETECTOR: PACKET_ZC_REQ_ANSWER_MACRO_DETECTOR.self,
    HEADER_ZC_CLOSE_MACRO_DETECTOR: PACKET_ZC_CLOSE_MACRO_DETECTOR.self,
    HEADER_ZC_ACK_PREVIEW_MACRO_DETECTOR: PACKET_ZC_ACK_PREVIEW_MACRO_DETECTOR.self,
    HEADER_ZC_PREVIEW_MACRO_DETECTOR_CAPTCHA: PACKET_ZC_PREVIEW_MACRO_DETECTOR_CAPTCHA.self,
    HEADER_ZC_ACK_PLAYER_AID_IN_RANGE: PACKET_ZC_ACK_PLAYER_AID_IN_RANGE.self,
    HEADER_ZC_NOTIFY_MEMBERINFO_TO_GROUPM: PACKET_ZC_NOTIFY_MEMBERINFO_TO_GROUPM.self,
    HEADER_ZC_ACK_TAKEOFF_EQUIP_ALL: PACKET_ZC_ACK_TAKEOFF_EQUIP_ALL.self,
    HEADER_ZC_DIALOG_TEXT_ALIGN: PACKET_ZC_DIALOG_TEXT_ALIGN.self,
    HEADER_ZC_GRADE_ENCHANT_MATERIAL_LIST: PACKET_ZC_GRADE_ENCHANT_MATERIAL_LIST.self,
    HEADER_ZC_GRADE_ENCHANT_ACK: PACKET_ZC_GRADE_ENCHANT_ACK.self,
    HEADER_ZC_GRADE_ENCHANT_BROADCAST_RESULT: PACKET_ZC_GRADE_ENCHANT_BROADCAST_RESULT.self,
    HEADER_ZC_SOULENERGY: PACKET_ZC_SOULENERGY.self,
    HEADER_ZC_OPEN_REFORM_UI: PACKET_ZC_OPEN_REFORM_UI.self,
    HEADER_ZC_ITEM_REFORM_ACK: PACKET_ZC_ITEM_REFORM_ACK.self,
    HEADER_ZC_RESPONSE_ENCHANT: PACKET_ZC_RESPONSE_ENCHANT.self,
    HEADER_ZC_GOLDPCCAFE_POINT: PACKET_ZC_GOLDPCCAFE_POINT.self,
    HEADER_ZC_DYNAMICNPC_CREATE_RESULT: PACKET_ZC_DYNAMICNPC_CREATE_RESULT.self,
    HEADER_ZC_ACK_CASH_BARGAIN_SALE_ITEM_INFO: PACKET_ZC_ACK_CASH_BARGAIN_SALE_ITEM_INFO.self,
    HEADER_ZC_NOTIFY_BARGAIN_SALE_SELLING: PACKET_ZC_NOTIFY_BARGAIN_SALE_SELLING.self,
    HEADER_ZC_NOTIFY_BARGAIN_SALE_CLOSE: PACKET_ZC_NOTIFY_BARGAIN_SALE_CLOSE.self,
    HEADER_ZC_ACK_COUNT_BARGAIN_SALE_ITEM: PACKET_ZC_ACK_COUNT_BARGAIN_SALE_ITEM.self,
    HEADER_ZC_ACK_GUILDSTORAGE_LOG: PACKET_ZC_ACK_GUILDSTORAGE_LOG.self,
    HEADER_ZC_ENTRY_QUEUE_INIT: PACKET_ZC_ENTRY_QUEUE_INIT.self,
    HEADER_ZC_SUMMON_HP_INIT: PACKET_ZC_SUMMON_HP_INIT.self,
    HEADER_ZC_SUMMON_HP_UPDATE: PACKET_ZC_SUMMON_HP_UPDATE.self,
    HEADER_ZC_REPUTE_INFO: PACKET_ZC_REPUTE_INFO.self,
    HEADER_ZC_TARGET_SPIRITS: PACKET_ZC_TARGET_SPIRITS.self,
    HEADER_ZC_CLEAR_DIALOG: PACKET_ZC_CLEAR_DIALOG.self,
    HEADER_ZC_BANKING_CHECK: PACKET_ZC_BANKING_CHECK.self,
    HEADER_ZC_ACK_BANKING_WITHDRAW: PACKET_ZC_ACK_BANKING_WITHDRAW.self,
    HEADER_ZC_ACK_BANKING_DEPOSIT: PACKET_ZC_ACK_BANKING_DEPOSIT.self,
    HEADER_ZC_ACK_CLOSE_BANKING: PACKET_ZC_ACK_CLOSE_BANKING.self,
    HEADER_ZC_ACK_OPEN_BANKING: PACKET_ZC_ACK_OPEN_BANKING.self,
    HEADER_ZC_PARTY_REQ_MASTER_TO_JOIN: PACKET_ZC_PARTY_REQ_MASTER_TO_JOIN.self,
    HEADER_ZC_PARTY_JOIN_REQ_ACK_FROM_MASTER: PACKET_ZC_PARTY_JOIN_REQ_ACK_FROM_MASTER.self,
    HEADER_ZC_ACK_SE_CASH_ITEM_LIST2: PACKET_ZC_ACK_SE_CASH_ITEM_LIST2.self,
    HEADER_ZC_INVENTORY_TAB: PACKET_ZC_INVENTORY_TAB.self,
    HEADER_ZC_SPIRITS_ATTRIBUTE: PACKET_ZC_SPIRITS_ATTRIBUTE.self,
    HEADER_ZC_HOSKILLINFO_LIST: PACKET_ZC_HOSKILLINFO_LIST.self,
    HEADER_ZC_HOSKILLINFO_UPDATE: PACKET_ZC_HOSKILLINFO_UPDATE.self,
    HEADER_ZC_ACK_OPENSTORE2: PACKET_ZC_ACK_OPENSTORE2.self,
    HEADER_ZC_KILLER_POINT: PACKET_ZC_KILLER_POINT.self,
    HEADER_ZC_KILLER_RANK: PACKET_ZC_KILLER_RANK.self,
    HEADER_ZC_ACK_RANKING: PACKET_ZC_ACK_RANKING.self,
    HEADER_ZC_UPDATE_RANKING_POINT: PACKET_ZC_UPDATE_RANKING_POINT.self,
    HEADER_ZC_ACK_RANKING2: PACKET_ZC_ACK_RANKING2.self,
    HEADER_ZC_DRESSROOM_OPEN: PACKET_ZC_DRESSROOM_OPEN.self,
    HEADER_ZC_GM_CHECKER: PACKET_ZC_GM_CHECKER.self,
    HEADER_ZC_EFST_SET_ENTER: PACKET_ZC_EFST_SET_ENTER.self,
    HEADER_ZC_ACK_SCHEDULER_CASHITEM: PACKET_ZC_ACK_SCHEDULER_CASHITEM.self,
    HEADER_ZC_NOTIFY_CLAN_CONNECTINFO: PACKET_ZC_NOTIFY_CLAN_CONNECTINFO.self,
    HEADER_ZC_ACK_CLAN_LEAVE: PACKET_ZC_ACK_CLAN_LEAVE.self,
    HEADER_ZC_NOTIFY_CLAN_CHAT: PACKET_ZC_NOTIFY_CLAN_CHAT.self,
    HEADER_ZC_STYLE_CHANGE_RES: PACKET_ZC_STYLE_CHANGE_RES.self,
    HEADER_ZC_GROUP_ISALIVE: PACKET_ZC_GROUP_ISALIVE.self,
    HEADER_ZC_GUILD_POSITION: PACKET_ZC_GUILD_POSITION.self,
    HEADER_ZC_REMOVE_EFFECT: PACKET_ZC_REMOVE_EFFECT.self,

    HEADER_ZC_RECOVER_PENALTY_OVERWEIGHT: PACKET_ZC_RECOVER_PENALTY_OVERWEIGHT.self,
    HEADER_ZC_SEND_SWAP_EQUIPITEM_INFO: PACKET_ZC_SEND_SWAP_EQUIPITEM_INFO.self,

    packet_header_achievementListType: PACKET_ZC_ALL_ACH_LIST.self,
    packet_header_achievementUpdateType: PACKET_ZC_ACH_UPDATE.self,

    HEADER_ZC_MSG_COLOR: PACKET_ZC_MSG_COLOR.self,                  // 0x9cd

    packet_header_rodexicon: PACKET_ZC_NOTIFY_UNREADMAIL.self,          // 0x9e7
    packet_header_rodexwriteresult: PACKET_ZC_WRITE_MAIL_RESULT.self,   // 0x9ed
//    packet_header_rodexmailList: ZC_ACK_MAIL_LIST,              // 0x9f0, 0xa7d, 0xac2
    packet_header_rodexgetzeny: PACKET_ZC_ACK_ITEM_FROM_MAIL.self,      // 0x9f2
    packet_header_rodexgetitem: PACKET_ZC_ACK_ITEM_FROM_MAIL.self,      // 0x9f4
    packet_header_rodexdelete: PACKET_ZC_ACK_DELETE_MAIL.self,          // 0x9f6

    HEADER_ZC_ACK_ADD_ITEM_RODEX: PACKET_ZC_ACK_ADD_ITEM_RODEX.self,    // 0xa05, 0xb3f
]
